config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:'', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'posts/index'

  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
   
  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'
  
  root to: 'pages#home'

  resources :blogs do 
    member do 
      get :toggle_status
    end
  end
  
  resources :posts

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
    
    has_many :technologies
    
    accepts_nested_attributes_for :technologies,
                                   reject_if: lambda { |attrs| attrs['name'].blank?}
    
    include Placeholder
    
    validates_presence_of :title, :body, :main_image, :thumb_image
    
    def self.angular
       where(subtitle: 'Angular') 
    end
    
    scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }
    
    after_initialize :set_defaults
    
    def set_defaults
       self.main_image ||=  Placeholder.image_generator(height: '600', width: '400')
       self.thumb_image ||= Placeholder.image_generator(height: '200', width: '350')
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  
  layout 'portfolio'
   access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
    def index
        @portfolio_items = Portfolio.all 
    end
    
    def new 
        @portfolio_item = Portfolio.new
        3.times { @portfolio_item.technologies.build }
    end
    
    def create 
        @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]))

        respond_to do |format|
          if @portfolio_item.save
            format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }
          else
            format.html { render :new }
          end
     end 
    end
    
    def edit 
        @portfolio_item = Portfolio.find(params[:id]);
    end
    
    def update
        
        @portfolio_item = Portfolio.find(params[:id]);
        
        respond_to do |format|
          if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
            format.html { redirect_to portfolios_path, notice: 'Portfolio was updated successfully.' }
          else
            format.html { render :edit }
          end
        end
    end
    
    def show 
        @portfolio_item = Portfolio.find(params[:id]);
    end
    
    def destroy
        
        @portfolio_item = Portfolio.find(params[:id]);
         
        @portfolio_item.destroy
            respond_to do |format|
              format.html { redirect_to portfolios_url, notice: 'Portfolio item was successfully destroyed.' } 
            end
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_portfolio_item.html.erb
<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
<p><%= portfolio_item.title %></p>
<p><%= portfolio_item.subtitle %></p>
<p><%= portfolio_item.body %></p>
<%= image_tag portfolio_item.thumb_image %></p>
<%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %>
<%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>

app/views/portfolios/edit.html.erb
<h3>Edit Portfolio item</h3>


<%= render 'shared/form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h3>Portfolio items</h3>

 
<%= link_to "Create new item", new_portfolio_path if logged_in?(:site_admin)%>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a new portfolio item</h1>

<%= render 'shared/form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<h3>Show</h3>

<%= image_tag @portfolio_item.main_image %>
<h1><%= @portfolio_item.title %></h1>
<em><%= @portfolio_item.subtitle %></em>
<p><%= @portfolio_item.body %></p>
<h2>Technologies used:</h2>

<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>
<% end %>